"""empty message

Revision ID: 267e95849cff
Revises: f87b3f1a8755
Create Date: 2024-07-29 23:55:14.480381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267e95849cff'
down_revision = 'f87b3f1a8755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotify_song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotify_song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
