"""empty message

Revision ID: 46131d785209
Revises: 91836ea37807
Create Date: 2024-07-29 19:23:06.022871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46131d785209'
down_revision = '91836ea37807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotify_account', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotify_account', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
