"""empty message

Revision ID: 64d720e2449f
Revises: 267e95849cff
Create Date: 2024-07-29 23:55:55.528993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64d720e2449f'
down_revision = '267e95849cff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotify_song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embed_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotify_song', schema=None) as batch_op:
        batch_op.drop_column('embed_url')

    # ### end Alembic commands ###
