"""empty message

Revision ID: 8b849203a31d
Revises: dd5ad9f35aaf
Create Date: 2024-07-30 00:35:18.190468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b849203a31d'
down_revision = 'dd5ad9f35aaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    

    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('liked_song', schema=None) as batch_op:
        batch_op.drop_column('popularity')
        batch_op.drop_column('image')
        batch_op.drop_column('album')
        batch_op.drop_column('artist')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
