"""empty message

Revision ID: 91836ea37807
Revises: 086899d8c8a5
Create Date: 2024-07-26 05:22:26.727362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91836ea37807'
down_revision = '086899d8c8a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotify_song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotify_song', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
