"""empty message

Revision ID: b179673f8151
Revises: bb05fbe34ff3
Create Date: 2024-07-31 01:23:18.984930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b179673f8151'
down_revision = 'bb05fbe34ff3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('top_artist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('genres', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('popularity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('top_artist', schema=None) as batch_op:
        batch_op.drop_column('popularity')
        batch_op.drop_column('genres')
        batch_op.drop_column('followers')

    # ### end Alembic commands ###
