"""empty message

Revision ID: dd5ad9f35aaf
Revises: 64d720e2449f
Create Date: 2024-07-30 00:12:06.476870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd5ad9f35aaf'
down_revision = '64d720e2449f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotify_song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))
        batch_op.drop_column('embed_url')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotify_song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('embed_url', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###
