"""empty message

Revision ID: e05fdd02b46f
Revises: 90e436d38585
Create Date: 2024-07-25 17:30:55.003768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e05fdd02b46f'
down_revision = '90e436d38585'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liked_songs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'song_id')
    )
    op.create_table('spotify_song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spotify_account_id', sa.Integer(), nullable=False),
    sa.Column('song_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=False),
    sa.Column('album', sa.String(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['spotify_account_id'], ['spotify_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liked_song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('spotify_song_id', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['spotify_song_id'], ['spotify_song.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('album', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('artist',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.drop_column('embed_link')
        batch_op.drop_column('spotify_id')
        batch_op.drop_column('popularity')
        batch_op.drop_column('release_date')
        batch_op.drop_column('label')
        batch_op.drop_column('cover_image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('label', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('release_date', sa.DATE(), nullable=False))
        batch_op.add_column(sa.Column('popularity', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('spotify_id', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('embed_link', sa.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('artist',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('duration')
        batch_op.drop_column('album')

    op.drop_table('liked_song')
    op.drop_table('spotify_song')
    op.drop_table('liked_songs')
    # ### end Alembic commands ###
