"""empty message

Revision ID: f0320e5466ed
Revises: 8b849203a31d
Create Date: 2024-07-30 01:55:16.233741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0320e5466ed'
down_revision = '8b849203a31d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotify_song', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('spotify_account_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('liked_song', schema=None) as batch_op:
        batch_op.alter_column('artist',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('spotify_song_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
