"""empty message

Revision ID: f87b3f1a8755
Revises: 46131d785209
Create Date: 2024-07-29 19:39:08.006882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f87b3f1a8755'
down_revision = '46131d785209'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotify_song', schema=None) as batch_op:
        batch_op.alter_column('spotify_account_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotify_song', schema=None) as batch_op:
        batch_op.alter_column('spotify_account_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
